name: Release

on:
  release:
    types: [published]

env:
  MIX_ENV: prod
  REQUIRE_VERSION_FILE: true

jobs:
  publish_to_hex:
    name: Publish to Hex.pm
    runs-on: ubuntu-latest
    container: hexpm/elixir:1.11.2-erlang-22.3.4.3-alpine-3.11.6
    steps:
      - uses: actions/checkout@v2

      - name: Write the release version to the version file
        run: |
          echo "Create version file for $GITHUB_REF"
          echo -n "${GITHUB_REF#v}" > version

      - name: Cache - deps/
        uses: actions/cache@v2
        with:
          path: deps/
          key: alpine-elixir-1.11.2-otp-22.3.4.3-deps-${{ hashFiles('**/mix.lock') }}
          restore-keys: alpine-elixir-1.11.2-otp-22.3.4.3-deps-

      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Cache - _build/
        uses: actions/cache@v2
        with:
          # Some erlang dependencies put build artifacts into `deps/` so we cache that too
          path: |
            _build/
            deps/
          key: alpine-elixir-1.11.2-otp-22.3.4.3-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: alpine-elixir-1.11.2-otp-22.3.4.3-build-

      - run: mix compile --warnings-as-errors

      - name: Publish
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
